name: API Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events for dev and main
  pull_request:
    branches: [ main, dev ]
  # Manual trigger API Tests
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Run Cypress API Tests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_COIN_MARKET_CAP_API_URL: ${{ secrets.COIN_MARKET_CAP_API_URL }}
        envkey_COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Runs a single command using the runners shell
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        start: npm start
        wait-on: http://localhost:3001
        browser: chrome
        headless: true
        spec: cypress/integration/*.spec.js
